### ISSUE TITLE
(question) Mark PR with "build started" creates a new version of a PR

### ISSUE THREAD

**Issue by artamonovkirill** [zarplata/concourse-git-bitbucket-pr-resource#15]
Given a job like
```
- name: test-pull-requests
  plan:
  - get: pull-request
    trigger: true
    version: every
  - get: node
  - put: pull-request
    params:
      state: INPROGRESS
      key: concourse-build
      description: Building on Concourse
  - task: test
    image: node
    privileged: true
    file: pull-request/config/concourse/tasks/test-pull-request.yml
    timeout: 1h
    on_success:
      put: pull-request
      params:
        state: SUCCESSFUL
        key: concourse-build
        description: Ready to merge
    on_failure:
      put: pull-request
      params:
        state: FAILED
        key: concourse-build
        description: Cannot merge
```
`INPROGRESS` put causes a new version of the same PR to be created in the resourse, so Concourse builds the same commit twice.
Is there a way to configure the plugin to ignore such type of PR updates?

**Comment by idr0id** [comment]
Hi, concourse is not available to skipping versions but we has the workaround.
You should add the resource with the same settings as `pull-request` for changing the build status only.

```
- name: test-pull-requests
  plan:
  - get: pull-request
    trigger: true
    version: every
  - get: node
  - put: pull-request-status
    params:
      state: INPROGRESS
      key: concourse-build
      description: Building on Concourse
```
