### ISSUE TITLE
Returns 404, with correct config

### ISSUE THREAD

**Issue by kamal-github** [zarplata/concourse-git-bitbucket-pr-resource#37]
For a private repository on Bitbucket Cloud (https://bitbucket.org), the resource returning 

```resource script '/opt/resource/check []' failed: exit status 22

stderr:
curl: (22) The requested URL returned error: 404 
``` 

My resource looks like this.
```
      base_url: https://bitbucket.org
      username: my-user-name
      password: my-password
      project: project-name
      repository: repo-name
      bitbucket_type: cloud
      git:
        uri: https://username@bitbucket.org/teamname/reponame.git
        private_key: <>
```

The example are not so clear in the README, what I am missing or making mistake?
