### ISSUE TITLE
Don't build when certain paths changed

### ISSUE THREAD

**Issue by ZaxR** [zarplata/concourse-git-bitbucket-pr-resource#41]
The readme mentions that `All params and source configuration of the original git-resource will be respected.` However, when I try to pass `ignore-paths` to the resource, builds are still triggered for changes only in those paths. Is there a way to not build on certain files being changed? My repos are on bitbucket server. Here's what I thought would work:

```
  - name: somename
    type: git-bitbucket-pr
    source:
      base_url: somebaseurl
      username: ((user))
      password: ((pass))
      project: proj
      repository: somename
      git:
        uri: someurl.git
        private_key: ((source-git-ssh-key))
      bitbucket_type: server
      ignore-paths:
        - '**/*.md'
        - .gitignore
```

The equivalent with the official git resource does work:
```
  - name: somename
    type: git
    source:
      uri: someurl.git
      branch: master
      tag_filter: v*
      private_key: ((source-git-ssh-key))
      ignore-paths:
        - '**/*.md'
        - .gitignore
```

Thank you!
