### ISSUE TITLE
paths parameter not working properly

### ISSUE THREAD

**Issue by vwfs-sasmoe** [zarplata/concourse-git-bitbucket-pr-resource#43]
Hi there,
it seems like the `paths` parameter is not working. At least not the way I expect it to work (same as in the [git-resource](https://github.com/concourse/git-resource).

The resource works as intended as long as I do not add the `paths` parameter. I always end up getting the following error in Concourse:
<img width="467" alt="grafik" src="https://user-images.githubusercontent.com/29733246/78176283-88411000-745c-11ea-81f1-fa13846303be.png">

Here is the current resource config (I replaced repo, project and user data):
```yaml
resources:
- name: bitbucket-pull-requests
  type: git-bitbucket-pr
  source:
    base_url: https://my.base.url
    username: myusername
    password: mypassword
    project: projectA
    repository: repoA
    git:
      uri: ssh://git@my.base.url/projectA/repoA.git
      private_key: mysuperprivaterepokey
    paths:
      - path/to/directory
```

I tried changing the values in `paths`, no luck. In addition, I tried adding the `pahts` parameter within the `git` config. It then does not throw an error anymore, but does not filter out any paths either.

The only idea I could come up with is that in [line 74 of the check file](https://github.com/zarplata/concourse-git-bitbucket-pr-resource/blob/master/assets/check#L43) the `uri` is constructed differently than in [line 43](https://github.com/zarplata/concourse-git-bitbucket-pr-resource/blob/master/assets/check#L43). 
In the working one (line 43) the path is `…/repos/${repository}${1}…`. in line 74 it is `…/repos/${repository}/…`.

Can anyone help to solve the problem?

System: Concourse v5.8.0, Bitbucket Server v4.5.2

Thanks in advance!
