### ISSUE TITLE
Put back to repository fails with no error message

### ISSUE THREAD

**Issue by fewknow** [zarplata/concourse-git-bitbucket-pr-resource#9]
My test pass but when the on_success of the job tries to `put` back to the resource it just fails.  There is not error output. 
![screen shot 2018-03-16 at 10 31 44 am](https://user-images.githubusercontent.com/22297806/37526327-66affc34-2905-11e8-87a3-7706a6ebd385.png)

Here is my resource code
```   
 name: pullrequest
    type: git-bitbucket-pr
    source:
      base_url: https://bitbucket.org
      bitbucket_type: cloud
      dir: pullrequest
      git:
        password: <redacted>
        uri: https://bitbucket.org/corvesta/helloworld.service
        username: cv-devops
      password: <redacted>
      project: corvesta
      repository: helloworld.service
      username: cv-devops
```
